#   _____ _                 ____  _            _
#  |_   _| |               |  _ \| |          | |
#    | | | |_ ___ _ __ ___ | |_) | | ___   ___| | _____ _ __
#    | | | __/ _ \ '_ ` _ \|  _ <| |/ _ \ / __| |/ / _ \ '__|
#   _| |_| ||  __/ | | | | | |_) | | (_) | (__|   <  __/ |
#  |_____|\__\___|_| |_| |_|____/|_|\___/ \___|_|\_\___|_|
#
#           ItemBlocker Configuration

# Set language (en/pl)
language: "en"

# Which actions to block
block-actions:
  crafting: true
  pickup: true
  drop: true
  use: true
  place: true
  armor: true
  inventory: true

# Bypass settings
bypass-permission:
  enabled: true

# Debug mode
debug-mode: false
